version: '3'
services:
  bitcoind:
    image: mocacinno/btc_testnet4
    privileged: true
    container_name: bitcoind
    entrypoint: ["/bin/sh", "-c", "cp /data/bitcoin.conf /data/testnet4/bitcoin.conf && bitcoind -chain=testnet4 -server -rpcuser=bitpats -rpcpassword=12345678@12 -rpcallowip=0.0.0.0 -datadir=/data/"]
    healthcheck:
      test: ["CMD", "bitcoin-cli", "-datadir=/data/", "getblockchaininfo"]
    volumes:
      - ./data:/data
    ports:
      - "8332:8332"  # RPC Port
      - "8333:8333"  # P2P Port (optional)
